#!/bin/bash
set -e

if [ $# -ne 1 ]; then
  echo "usage: $0 NAME"
  exit 1
fi

git branch --no-track "$1" origin/tmpl
echo "Created: $1"
git checkout "$1"
echo "Remember to run:"
echo "    git push -u origin $1"
