#!/bin/bash
set -e

cd $(dirname "$0")
export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get -o Dpkg::Options::='--force-confold' dist-upgrade -y

apt-get clean
rm -rf /var/lib/apt/lists/*
rm "$0"
