#!/bin/bash
set -e

cd $(dirname "$0")
export DEBIAN_FRONTEND=noninteractive

cat > /usr/sbin/policy-rc.d <<- EOF
#!/bin/sh
exit 101
EOF

cat > /etc/apt/apt.conf.d/99-no-install-recommends <<- EOF
APT::Install-Recommends "false";
APT::Install-Suggests "false";
EOF

mv webupd8team-java-trusty.list /etc/apt/sources.list.d/
mv webupd8team-java.gpg         /etc/apt/trusted.gpg.d/
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true \
  | debconf-set-selections

apt-get update
apt-get -o Dpkg::Options::='--force-confold' dist-upgrade -y
apt-get install -y ca-certificates oracle-java8-installer

apt-get clean
rm -rf /var/cache/oracle-jdk8-installer
rm -rf /var/lib/apt/lists/*
rm "$0"
du -h /tmp /var/cache >&2
