#!/bin/bash
set -e

cd $(dirname "$0")
export DEBIAN_FRONTEND=noninteractive

cat > /usr/sbin/policy-rc.d <<- EOF
#!/bin/sh
exit 101
EOF

cat > /etc/apt/apt.conf.d/99-no-install-recommends <<- EOF
APT::Install-Recommends "false";
APT::Install-Suggests "false";
EOF

apt-get update
apt-get -o Dpkg::Options::='--force-confold' dist-upgrade -y

apt-get clean
rm -rf /var/lib/apt/lists/*
rm "$0"
du -h /tmp /var/cache >&2
